/** Enum for server request endpoints */
enum REQUEST_ENDPOINTS {
    STARTUP = "/v2/api/startup",
    LOGIN = "/api/v2/login",
    LOGOUT = "/api/logout",
    CLOSE_SCREEN = "/api/closeScreen",
    DISPATCH_ACTION = "/v2/api/dispatchAction",
    OPEN_SCREEN = "/api/v2/openScreen",
    DEVICE_STATUS="/v2/api/deviceStatus",
    UPLOAD = "/upload",
    DELETE_RECORD = "/v2/api/dal/deleteRecord",
    INSERT_RECORD = "/v2/api/dal/insertRecord",
    SELECT_ROW = "/v2/api/dal/selectRecord",
    SELECT_COLUMN = "/v2/api/dal/selectColumn",
    SELECT_TREE = "/v2/api/dal/selectRecordTree",
    FETCH="/v2/api/dal/fetch",
    META_DATA="/v2/api/dal/metaData",
    FILTER = "/v2/api/dal/filter",
    SET_VALUE = "/v2/api/comp/setValue",
    SET_VALUES = "/v2/api/dal/setValues",
    SELECT_TAB = "/v2/api/comp/selectTab",
    CLOSE_TAB = "/v2/api/comp/closeTab",
    CLOSE_POPUP_MENU = "/v2/api/comp/closePopupMenu ",
    SAVE = "/api/save",
    DAL_SAVE = "/v2/api/dal/save",
    SORT = "/v2/api/dal/sort",
    CHANGE_PASSWORD = "/api/changePassword",
    RESET_PASSWORD = "/api/resetPassword",
    SET_SCREEN_PARAMETER = "/api/setScreenParameter",
    MOUSE_CLICKED = "/v2/api/mouseClicked",
    MOUSE_PRESSED = "/v2/api/mousePressed",
    MOUSE_RELEASED = "/v2/api/mouseReleased",
    RELOAD = "/api/reload",
    UI_REFRESH = "/v2/api/uiRefresh",
    ROLLBACK = "/api/rollback",
    CHANGES = "/api/changes",
    FOCUS_GAINED = "/v2/api/focusGained",
    FOCUS_LOST = "/v2/api/focusLost",
    CLOSE_FRAME = "/api/closeFrame",
    CLOSE_CONTENT = "/api/closeContent",
    REOPEN_SCREEN = "/api/reopenScreen",
    EXIT = "/v2/api/exit",
    BOUNDS = "/v2/api/comp/bounds"
}
export default REQUEST_ENDPOINTS